USEMODULE_INCLUDES_feedforward_combiner_controller := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_feedforward_combiner_controller)

PROTOBUF_PATH_feedforward_combiner_controller := $(LAST_MAKEFILEDIR)
PROTOBUF_PATH += $(PROTOBUF_PATH_feedforward_combiner_controller)
