APPLICATION = trapezoidal_profile_test

BOARD ?= cogip-native

# Motion control common (includes TrapezoidalProfile)
USEMODULE += motion_control_common

# Utils (required by motion_control_common)
USEMODULE += utils

# Embedded Template Library
USEPKG += etl

include ../../Makefile.include
