USEMODULE_INCLUDES_profile_tracker_controller := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_profile_tracker_controller)

PROTOBUF_PATH_profile_tracker_controller := $(LAST_MAKEFILEDIR)
PROTOBUF_PATH += $(PROTOBUF_PATH_profile_tracker_controller)
