---
dist: bionic
language: c
env:
      - PLATFORM=cogip2019-cortex
      - PLATFORM=cogip2019-cortex-simulation
before_install:
      - export TOOLCHAIN_NAME=gcc-arm-none-eabi-8-2018-q4-major
      - export PATH=/opt/toolchain/$TOOLCHAIN_NAME/bin:$PATH
      - export RIOTBASE=/tmp/RIOT
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
      - sudo apt-get update -qq
      - mkdir /opt/toolchain
install:
      - uname -a
      - wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2018q4/$TOOLCHAIN_NAME-linux.tar.bz2
      - tar -C /opt/toolchain/ -xf $TOOLCHAIN_NAME-linux.tar.bz2
      - sudo apt-get install -qq gcc-8 gcc-8-multilib gcc-multilib libc6-dev
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 1
      - gcc --version
      - arm-none-eabi-gcc --version
before_script:
      - git clone https://github.com/RIOT-OS/RIOT.git $RIOTBASE -b master --depth 1
script:
      - cd platforms/$PLATFORM
      - make -j$(nproc)
      - make distclean
