---
dist: focal
language: c
env:
before_install:
      - export RIOTBASE=/tmp/RIOT
      - sudo apt-get update -qq
install:
      - sudo apt-get install -qq build-essential gcc-multilib gcc-arm-none-eabi libnewlib-arm-none-eabi
      - gcc --version
      - arm-none-eabi-gcc --version
before_script:
      - git clone https://github.com/RIOT-OS/RIOT.git $RIOTBASE -b 2020.07 --depth 1
script:
      - make
      - make distclean
