# Required features
FEATURES_REQUIRED += cpp
FEATURES_REQUIRED += libstdcpp

# Required modules
USEMODULE += malloc_thread_safe
USEMODULE += malloc_tracing
USEMODULE += thread
USEMODULE += ztimer_sec
USEMODULE += ztimer_msec
USEMODULE += ztimer_usec

# Required packages
USEPKG += etl
