USEMODULE_INCLUDES_polar_parallel_meta_controller := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_polar_parallel_meta_controller)

PROTOBUF_PATH_polar_parallel_meta_controller := $(LAST_MAKEFILEDIR)
PROTOBUF_PATH += $(PROTOBUF_PATH_polar_parallel_meta_controller)
