# Use newlib instead of newlib_nano to support C++ exceptions
DISABLE_MODULE += newlib_nano

USEMODULE += cpp11-compat

ifneq ($(CPU),native)
	ifneq ($(TRACEFD_SDCARD_SPI_DEV),)
		USEMODULE += mtd_sdcard
		USEMODULE += vfs
		USEMODULE += fatfs_vfs
	endif
endif
