# Use newlib instead of newlib_nano to support C++ exceptions
DISABLE_MODULE += newlib_nano

USEMODULE += cpp11-compat

ifneq ($(CPU),native)
	USEMODULE += mtd_sdcard
	USEMODULE += vfs
	USEMODULE += fatfs_vfs
endif
