APPLICATION = cup2025-robot1-lift

BOARD ?= cogip-board

# Platform
USEMODULE += pf-robot-motors

# Update maximum number of motors for actuators
CFLAGS += -DCONFIG_MOTOR_DRIVER_MAX=2

include ../../Makefile.include
