APPLICATION = cup2024-robot-motors

BOARD ?= cogip-board

# Platform
USEMODULE += pf-robot-motors

# Update maximum number of motors for actuators
CFLAGS += -DCONFIG_MOTOR_DRIVER_MAX=2

include ../../Makefile.include
