# define the cpu used by the cogip2018-cortex board
export CPU = stm32f4
export CPU_MODEL = stm32f446re

export DEBUG_ADAPTER ?= stlink
export STLINK_VERSION ?= 2

# set default port depending on operating system
PORT_LINUX ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.SLAB_USBtoUART*)))

# setup serial terminal
include $(RIOTMAKE)/tools/serial.inc.mk

# this board uses openocd
include $(RIOTMAKE)/tools/openocd.inc.mk
