APPLICATION = lds01_dma_example

BOARD ?= nucleo-f446re

USEMODULE += shell
USEMODULE += xtimer
USEMODULE += event
USEMODULE += lds01_dma

INCLUDES += -I$(CURDIR)/include

include ../../Makefile.include
