# name of your application
APPLICATION = shell-menu

# If no BOARD is found in the environment, use this default:
BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../..

USEMODULE += shell_menu
USEMODULE += ps

include ../../Makefile.include
