# name of your application
APPLICATION = shell-menu

# If no BOARD is found in the environment, use this default:
BOARD ?= native

USEMODULE += shell_menu
USEMODULE += ps

include ../../Makefile.include
