APPLICATION = controller_robot_test

BOARD ?= cogip-native

USEMODULE += dualpid_meta_controller
USEMODULE += pid_ng
USEMODULE += platform_engine
USEMODULE += polar_parallel_meta_controller
USEMODULE += pose_pid_controller
USEMODULE += pose_straight_filter
USEMODULE += speed_pid_controller
USEMODULE += speed_filter
USEMODULE += pid_ng

# Shell
USEMODULE += ps
USEMODULE += shell
USEMODULE += shell_commands

USEPKG += etl

include ../../Makefile.include
