NATIVEINCLUDES += -DBOARD_NATIVE
include $(RIOTBASE)/boards/native/Makefile.include

# Set onboard transceiver loop delay, mandatory so set fake value
CFLAGS += -DCONFIG_FDCAN_DEVICE_TRANSCEIVER_LOOP_DELAY=0
