USEMODULE += periph_common

ifneq (,$(filter periph_gpio,$(USEMODULE)))
  USEMODULE += periph_gpio_mock
endif

ifneq (,$(filter periph_can,$(FEATURES_USED)))
  USEMODULE += fdcan
  ifeq ($(OS),Linux)
  	USEPKG += libsocketcan
    CFLAGS += -DCAN_DLL_NUMOF=1
  endif
endif

USEMODULE += native_drivers

# FlashDB modules
USEMODULE += flashdb_kvdb          # Key-Value database module
USEMODULE += flashdb_mtd           # MTD backend for FlashDB

# MTD(Memory Technology Device) driver
USEMODULE += mtd_emulated # Use emulated MTD in RAM for native
