USEMODULE_INCLUDES_common_controller := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_common_controller)

PROTOBUF_PATH_common_controller := $(LAST_MAKEFILEDIR)
PROTOBUF_PATH += $(PROTOBUF_PATH_common_controller)
