# Define the cpu used
CPU = stm32
CPU_MODEL = stm32f446re

# Put defined MCU peripherals here (in alphabetical order)
FEATURES_PROVIDED += periph_gpio
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += periph_qdec
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart

-include $(RIOTCPU)/stm32/Makefile.features
