# We use shared STM32 configuration snippets
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

# Default board USB port on host (FTDI based)
PORT = "/dev/ttyUSB0"

# Setup of programmer and serial is shared between STM32 based boards
include $(RIOTMAKE)/boards/stm32.inc.mk

# Set onboard transceiver loop delay
CFLAGS += -DCONFIG_FDCAN_DEVICE_TRANSCEIVER_LOOP_DELAY=130
