ifneq (,$(filter stdio_uart,$(USEMODULE)))
  FEATURES_REQUIRED += periph_lpuart
endif

# Disable automatic init of I2C as some boards have different IOs mapping
DISABLE_MODULE += periph_init_i2c

USEMODULE += mpu_stack_guard

# FlashDB modules
USEMODULE += flashdb_kvdb          # Key-Value database module
USEMODULE += flashdb_mtd           # MTD backend for FlashDB

# MTD(Memory Technology Device) driver
USEMODULE += mtd_flashpage # Use internal flash via flashpage interface
