USEMODULE_INCLUDES_passthrough_pose_pid_controller := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_passthrough_pose_pid_controller)

PROTOBUF_PATH_passthrough_pose_pid_controller := $(LAST_MAKEFILEDIR)
PROTOBUF_PATH += $(PROTOBUF_PATH_passthrough_pose_pid_controller)
