#!/bin/bash

# Filter to only check .c and .h files
FILES_TO_CHECK=$(find . -name '*.c' -o -name '*.h')
for FILE in ${FILES_TO_CHECK}; do
    uncrustify -q -l C -c tools/codingrules-uncrustify-riot.cfg {} $FILE
done

# Info: uncrustify append ".uncrustify" to uncompliant files
#   ie: "./robotics/odometry.c" become "./robotics/odometry.c.uncrustify"

# Search *.uncrustify files generated by uncrustify when file are not compliant with our rules
UNCRUSTIFIED_FILES=$(find . -name '*.uncrustify')
EXIT_STATUS=0
for FILE in ${UNCRUSTIFIED_FILES}; do
    ORIGIN_FILE=$(echo ${FILE%.*}) # Remove the string ".uncrustify" from the filename
    diff --color -u ${ORIGIN_FILE} ${FILE}
    if [ $? -ne 0 ]; then
        EXIT_STATUS=1
    fi
    rm ${FILE}
done

exit ${EXIT_STATUS}
