USEMODULE_INCLUDES_speed_pid_controller := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_speed_pid_controller)

PROTOBUF_PATH_speed_pid_controller := $(LAST_MAKEFILEDIR)
PROTOBUF_PATH += $(PROTOBUF_PATH_speed_pid_controller)
