USEMODULE_INCLUDES_dualpid_meta_controller := $(LAST_MAKEFILEDIR)/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_dualpid_meta_controller)

PROTOBUF_PATH_dualpid_meta_controller := $(LAST_MAKEFILEDIR)
PROTOBUF_PATH += $(PROTOBUF_PATH_dualpid_meta_controller)
